[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting = "6GxK9ASmrHBBFJvLkcJRGmkqvmhG4XWFqpDPMdox5uE6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "CQWpCq6BtFGNovpXrrZWtx7jNWz2XKX6yUneKu7rPZbs"
program = "artifacts/arcium_program_0.1.25.so"

[test.validator]
bind_address = "0.0.0.0"
ledger = ".anchor/test-ledger"
rpc_port = 8899


[[test.validator.account]]
address = "VWNZDN2cTXLxJCHecGWRvY5qPHJus1eAVtkAEDNb9iH"
filename = "artifacts/arcium_clock.json"

[[test.validator.account]]
address = "AXih6FLA9s3L5ro73kVKFz9dyYarA1a4hLE7gNqcoKuZ"
filename = "artifacts/arcium_pool.json"

[[test.validator.account]]
address = "67caFht6JPaJzkgbT8EJ8rd7efSVVc65dnNJgvQckwNW"
filename = "artifacts/arcium_pool_ata.json"

[[test.validator.account]]
address = "BY1ak2NZ2h9sFfsrp2kxSQ1P9cRcQKdGGpgZXYjq1gn9"
filename = "artifacts/wallet_acc_BY1a_1gn9.json"

[[test.validator.account]]
address = "BoVUVSJAhob2cvM5z4JZTdS6VWRSznh3bbzQD1TFjvDP"
filename = "artifacts/arx_mint_BY1a_1gn9.json"

[[test.validator.account]]
address = "HR9k9ALEhnFSpdrJ8Tq6EukhZaqpuCEnGDKZqV7dxuat"
filename = "artifacts/arx_ata_user_BY1a_1gn9.json"

[[test.validator.account]]
address = "7M36kkHWMhLL9q2v7khUiQqnVzzcqy7U2wLAT8ZJi2Xi"
filename = "artifacts/primary_stake_acc_BY1a_1gn9.json"

[[test.validator.account]]
address = "BWqAHKYDdEp9JNBL45WM4WpcLkXoJF5BvMnFhzAqqAYT"
filename = "artifacts/stake_queue_acc_BY1a_1gn9.json"

[[test.validator.account]]
address = "BG2jkxu7gXysxrmt2t5P1cBTmcULbxHgyWs2FW14SbiY"
filename = "artifacts/operator_acc_BY1a_1gn9.json"

[[test.validator.account]]
address = "7KfGNFoEjWBv3giYW8ZhmJYxZMpDQ8N5VurQV98KAPym"
filename = "artifacts/arx_node_BY1a_1gn9.json"

[[test.validator.account]]
address = "ariZN4ANYnFyfnF12mmUuCchjawFXnepyrWdEQakFtP"
filename = "artifacts/wallet_acc_ariZ_kFtP.json"

[[test.validator.account]]
address = "BoVUVSJAhob2cvM5z4JZTdS6VWRSznh3bbzQD1TFjvDP"
filename = "artifacts/arx_mint_ariZ_kFtP.json"

[[test.validator.account]]
address = "79hykNQMNeXvcpYDM2buEz1kGNnFBgnGvKPTyTUnCAEj"
filename = "artifacts/arx_ata_user_ariZ_kFtP.json"

[[test.validator.account]]
address = "DFgcMv2v6Pofp4efstBgBGUP241B1pHftsEoSVgf1X6b"
filename = "artifacts/primary_stake_acc_ariZ_kFtP.json"

[[test.validator.account]]
address = "G79scK4hrtbacLwtnUsYbhFcbW6R1jxk3GwLDQnVud8f"
filename = "artifacts/stake_queue_acc_ariZ_kFtP.json"

[[test.validator.account]]
address = "4AXAddC82khUkcEpwVDmdvZ1qgQQqai7DU3NT3fHivkc"
filename = "artifacts/operator_acc_ariZ_kFtP.json"

[[test.validator.account]]
address = "6kQZs3uTZy42aV1wjDTPKST1DJRWjeY3VayyoaRDZYnj"
filename = "artifacts/arx_node_ariZ_kFtP.json"

[[test.validator.account]]
address = "EP5C8AfUNTdP1m41gik4oZzFGRud8ES3e3o2CHmqYtqs"
filename = "artifacts/cluster_acc_0.json"

[[test.validator.account]]
address = "E7ijVtJTvDcdCYCnZuMcojRYiQihv4Dg7nUG9YappbmU"
filename = "artifacts/reveal_result_raw_circuit_0.json"

[[test.validator.account]]
address = "HRi3wjZPgnRj2uJV3H592bAri6w2LmqjPjaPjoDYLe6j"
filename = "artifacts/vote_raw_circuit_0.json"

[[test.validator.account]]
address = "4br7L5LX4ot4Vhqdxeyh7DFLmA377NvbbWFWdrpDXxnx"
filename = "artifacts/mxe_acc.json"

[[test.validator.account]]
address = "69ffyqkBjAkWqzCGzUhALgFaGcWHG97nBdxci2u3dzYA"
filename = "artifacts/mempool_acc.json"

[[test.validator.account]]
address = "7u9vuCyon1iVbSWLubhMSV2AH5AkWrxjVn2JyKWVC6Tb"
filename = "artifacts/executing_pool_acc.json"
