[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting = "EGRyBhhe9pzvoznJuQh5x5Dx5V2eKQv1AwWdTsEMEYEQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[test.validator]
[[test.genesis]]
address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/Users/arihantbansal/Developer/arcium/examples/voting/artifacts/arcium_program_0.1.40.so"


[[test.validator.account]]
address = "FHriyvoZotYiFnbUzKFjzRSb2NiaC8RPWY7jtKuKhg65"
filename = "artifacts/arcium_clock.json"

[[test.validator.account]]
address = "DXHqHhBGNM58RLk438UiEbGe9137A7zJc6JHKN3qMZoB"
filename = "artifacts/arcium_pool.json"

[[test.validator.account]]
address = "FF1ZjqVRQDfd6N5LaUh1i2PQ946vQjHpnbDuAyaCXUdQ"
filename = "artifacts/arcium_pool_ata.json"

[[test.validator.account]]
address = "BoVUVSJAhob2cvM5z4JZTdS6VWRSznh3bbzQD1TFjvDP"
filename = "artifacts/arx_mint.json"

[[test.validator.account]]
address = "ariZN4ANYnFyfnF12mmUuCchjawFXnepyrWdEQakFtP"
filename = "artifacts/wallet_acc_ariZ_kFtP.json"

[[test.validator.account]]
address = "79hykNQMNeXvcpYDM2buEz1kGNnFBgnGvKPTyTUnCAEj"
filename = "artifacts/arx_ata_ariZ_kFtP.json"

[[test.validator.account]]
address = "3FaSiLGLvg6PmEt7gAMyJPpHfTvuwLcunGJYDy1Fq5VZ"
filename = "artifacts/callback_server_acc_3FaS_q5VZ.json"

[[test.validator.account]]
address = "E5rmBy7ksyNXQujQVEwuQHimrCVhZUT1bXQnSzCESKbk"
filename = "artifacts/wallet_acc_E5rm_SKbk.json"

[[test.validator.account]]
address = "92YjC9q5dM1FCFLt5oJi1pEFLdYJmMuZPx2pjTUPpVSx"
filename = "artifacts/arx_ata_E5rm_SKbk.json"

[[test.validator.account]]
address = "Gaz4s4pzeRC6sS1ou4NK1J99iQ4iCck6AwwC65JVn5Uj"
filename = "artifacts/primary_stake_acc_E5rm_SKbk.json"

[[test.validator.account]]
address = "C1xgkdqsLbiaQnxHiPX6x7opuPsRBX3Nbt1fsBfQrVVp"
filename = "artifacts/stake_queue_acc_E5rm_SKbk.json"

[[test.validator.account]]
address = "BM7RvrU6C1GKrCD978xX2cWoEudsb6vA2iuKpMCPNzjT"
filename = "artifacts/operator_acc_E5rm_SKbk.json"

[[test.validator.account]]
address = "ELoRR19zrps1G3UYKcAxr7LKbw3kbqkVUXVY9dETMWN7"
filename = "artifacts/arx_node_E5rm_SKbk.json"

[[test.validator.account]]
address = "3F248ywWWZ5pXHrGyAY8HKb73GrVkpABdjPqPDMQiny5"
filename = "artifacts/wallet_acc_3F24_iny5.json"

[[test.validator.account]]
address = "FfCu7iqkAWJcsnby9uBTdQsvGkJoAsm6Rim3TzTtTqYS"
filename = "artifacts/arx_ata_3F24_iny5.json"

[[test.validator.account]]
address = "35Qnw5R7HCHggxWugor7MD4oAJc8TCKSRWewJzFKzyfj"
filename = "artifacts/primary_stake_acc_3F24_iny5.json"

[[test.validator.account]]
address = "518FpGeB2EQMN7S2heu58ARU5ojRpxCTaEdf1zFRfnFc"
filename = "artifacts/stake_queue_acc_3F24_iny5.json"

[[test.validator.account]]
address = "HDutPsjSi3BsyyCebEwco5keWimLZCZK4hd8zppfnYjy"
filename = "artifacts/operator_acc_3F24_iny5.json"

[[test.validator.account]]
address = "XdfSwb8ZajhN7CerfBSJVhyfx5fyLtv34QVKSRgMFA9"
filename = "artifacts/arx_node_3F24_iny5.json"

[[test.validator.account]]
address = "GgSqqAyH7AVY3Umcv8NvncrjFaNJuQLmxzxFxPoPW2Yd"
filename = "artifacts/cluster_acc_0.json"

[[test.validator.account]]
address = "GPzDhoofXLsa7osdFMkbxnEXFnZoXvk2r9xgXuWdoYaU"
filename = "artifacts/vote_raw_circuit_0.json"

[[test.validator.account]]
address = "5iU9vGzwsv9Jj6CgWXotCjx8SE8e1JGUYtZXQe9HFtDK"
filename = "artifacts/add_together_raw_circuit_0.json"

[[test.validator.account]]
address = "FHyiBWAqzdwDL88QssDzNcsgBNcegF5uPnUpE52V71Md"
filename = "artifacts/reveal_result_raw_circuit_0.json"

[[test.validator.account]]
address = "736PhPjZuo9nCeRZ8xPY8YUExRiPX1u1ek615HHX8MMw"
filename = "artifacts/init_vote_stats_raw_circuit_0.json"

[[test.validator.account]]
address = "6Be3H5ELkgAB7wuCnovK89ZEU6jf9kWwfkrxPByREdVH"
filename = "artifacts/mxe_acc.json"

[[test.validator.account]]
address = "7v6v5NC8kkwV9T4Y7gStoupjMoAeSUBvy46EL1bEnUSU"
filename = "artifacts/mempool_acc.json"

[[test.validator.account]]
address = "2AaM9cUT8LsMew8RoDJ2SzdgHyAvUrycQ7x2jibcwxnB"
filename = "artifacts/executing_pool_acc.json"
