[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting = "GPTg3qxKdtm9gZQhY7SwBiuUykmT9WTi8SgjTuQyumkX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[test.validator]
[[test.genesis]]
address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/Users/arihantbansal/Developer/arcium/examples/voting/artifacts/arcium_program_0.1.37.so"


[[test.validator.account]]
address = "FHriyvoZotYiFnbUzKFjzRSb2NiaC8RPWY7jtKuKhg65"
filename = "artifacts/arcium_clock.json"

[[test.validator.account]]
address = "DXHqHhBGNM58RLk438UiEbGe9137A7zJc6JHKN3qMZoB"
filename = "artifacts/arcium_pool.json"

[[test.validator.account]]
address = "FF1ZjqVRQDfd6N5LaUh1i2PQ946vQjHpnbDuAyaCXUdQ"
filename = "artifacts/arcium_pool_ata.json"

[[test.validator.account]]
address = "BoVUVSJAhob2cvM5z4JZTdS6VWRSznh3bbzQD1TFjvDP"
filename = "artifacts/arx_mint.json"

[[test.validator.account]]
address = "ariZN4ANYnFyfnF12mmUuCchjawFXnepyrWdEQakFtP"
filename = "artifacts/wallet_acc_ariZ_kFtP.json"

[[test.validator.account]]
address = "79hykNQMNeXvcpYDM2buEz1kGNnFBgnGvKPTyTUnCAEj"
filename = "artifacts/arx_ata_ariZ_kFtP.json"

[[test.validator.account]]
address = "GLph7DubGuJNAKxwLZ2tghvj3viebzXJ6t3rV8KSWSiJ"
filename = "artifacts/callback_server_acc_GLph_WSiJ.json"

[[test.validator.account]]
address = "7RNmD3syhii9kWFtabgaoA1XCqU5FhKBs1PucSs9TDnj"
filename = "artifacts/wallet_acc_7RNm_TDnj.json"

[[test.validator.account]]
address = "5MHTNzr4VnFVe7E1E5Ex7o1RT3Q8pg2D6HC8ryxtQSRo"
filename = "artifacts/arx_ata_7RNm_TDnj.json"

[[test.validator.account]]
address = "Eo7KQqaaZsoSZVowhQQriKXofRBgKhhUHNzG8kiHCqGP"
filename = "artifacts/primary_stake_acc_7RNm_TDnj.json"

[[test.validator.account]]
address = "8Z1GeaKcGMfJ8s482Z9NbmNYRwfJfhRQnxfWKDhCnmYt"
filename = "artifacts/stake_queue_acc_7RNm_TDnj.json"

[[test.validator.account]]
address = "3BPsCzJgbdMd27HpsvYoKHPajV7SFKV2qhYSUjnLXwS4"
filename = "artifacts/operator_acc_7RNm_TDnj.json"

[[test.validator.account]]
address = "ELoRR19zrps1G3UYKcAxr7LKbw3kbqkVUXVY9dETMWN7"
filename = "artifacts/arx_node_7RNm_TDnj.json"

[[test.validator.account]]
address = "GgSqqAyH7AVY3Umcv8NvncrjFaNJuQLmxzxFxPoPW2Yd"
filename = "artifacts/cluster_acc_0.json"

[[test.validator.account]]
address = "HfBNaGaQg7dwhyFgB1ePgjsuBs8gzhMaupT8ZRDC2KF3"
filename = "artifacts/reveal_result_raw_circuit_0.json"

[[test.validator.account]]
address = "DznpHyYvi1Aj9dLqyKfPCUZCbQVLqSUBy8ybdxHDGq1H"
filename = "artifacts/vote_raw_circuit_0.json"

[[test.validator.account]]
address = "DqKJVGmdmLghKBzeMRkxYv6nRo6AbnB2X3HZ1F5LZJha"
filename = "artifacts/init_vote_stats_raw_circuit_0.json"

[[test.validator.account]]
address = "DoqjrjsiYhnsWSPWf36zyUUvtEDU81N58nE6KRJQAsky"
filename = "artifacts/mxe_acc.json"

[[test.validator.account]]
address = "EmYQdFLyhYGMpSyw2KFG6UxwpQyVg3H78a5TUjNzJZ5T"
filename = "artifacts/mempool_acc.json"

[[test.validator.account]]
address = "4BhMUN2ZZWs9N3XjNQ173doP6tsXhtYuJE59qTHsPcoh"
filename = "artifacts/executing_pool_acc.json"
