name: "Setup"
description: "Setup"
runs:
  using: "composite"
  steps:
    - run: echo "RUST_VERSION=1.85.0" >> $GITHUB_ENV
      shell: bash
    - run: echo "ANCHOR_VERSION=0.31.1" >> $GITHUB_ENV
      shell: bash
    - run: echo "DEFAULT_ARCIUM_PROGRAMS_VERSION=0.1.45" >> $GITHUB_ENV
      shell: bash
    - run: echo "SOLANA_CLI_VERSION=2.1.6" >> $GITHUB_ENV
      shell: bash
    - run: echo "CARGO_TERM_COLOR=always" >> $GITHUB_ENV
      shell: bash
    - run: echo "RUSTFLAGS=-Dwarnings" >> $GITHUB_ENV
      shell: bash
    - run: echo "CARGO_NET_GIT_FETCH_WITH_CLI=true" >> $GITHUB_ENV
      shell: bash
    - run: echo "ARCUP_VERSION=0.1.45" >> $GITHUB_ENV
      shell: bash

    # Setup Rust with specific version
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.85.0
        override: true
        components: clippy

    - run: rustup update
      shell: bash

    # Cache cargo registry
    - uses: actions/cache@v4
      name: Cache Cargo Registry
      with:
        path: |
          ~/.cargo/registry/
          ~/.cargo/git/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Set git-fetch-with-cli for Cargo
      run: |
        echo '[net]' > ~/.cargo/config.toml
        echo 'git-fetch-with-cli = true' >> ~/.cargo/config.toml
      shell: bash
