name: "Setup"
description: "Setup"
runs:
  using: "composite"
  steps:
    # Use the source build for now
    - run: echo "ANCHOR_VERSION=0" >> $GITHUB_ENV
      shell: bash
    - run: echo "ANCHOR_COMMIT_HASH=06527e57c3e59683c36eb0a5c69ee669100b42e5" >> $GITHUB_ENV
      shell: bash
    - run: echo "DEFAULT_ARCIUM_PROGRAMS_VERSION=0.1.32" >> $GITHUB_ENV
      shell: bash
    - run: echo "DUMMY_PROGRAM_COMMIT_HASH=17302d9441f114516ad9b11aa5d77fe1a8b942de" >> $GITHUB_ENV
      shell: bash
    - run: echo "SOLANA_CLI_VERSION=1.18.17" >> $GITHUB_ENV
      shell: bash
    - run: echo "CARGO_TERM_COLOR=always" >> $GITHUB_ENV
      shell: bash
    - run: echo "RUSTFLAGS=-Dwarnings" >> $GITHUB_ENV
      shell: bash
    - run: echo "CARGO_NET_GIT_FETCH_WITH_CLI=true" >> $GITHUB_ENV
      shell: bash
    - name: Set git-fetch-with-cli for Cargo
      # Overwrite the file first since it might be cached and then append (> vs >>)
      run: |
        echo '[net]' > ~/.cargo/config.toml
        echo 'git-fetch-with-cli = true' >> ~/.cargo/config.toml
      shell: bash
