name: "Setup Anchor"
description: "Setup Anchor"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup/
    - uses: ./.github/actions/setup-solana/
    - uses: actions/cache@v4
      name: Cache Anchor CLI
      id: cache-anchor-cli
      with:
        path: |
          ~/.cargo/bin/anchor
        key: anchor-cli-${{ runner.os }}-v0004-${{ env.ANCHOR_VERSION }}
        save-always: true
    - run: |
        sudo apt-get update
        sudo apt install build-essential cmake pkg-config libudev-dev
        cargo install --git https://github.com/solana-foundation/anchor --tag v${{ env.ANCHOR_VERSION }} anchor-cli --locked --force
      shell: bash
      if: steps.cache-anchor-cli.outputs.cache-hit != 'true'
    - name: Run Anchor CLI
      run: anchor --version
      shell: bash