name: "Setup Solana"
description: "Setup Solana"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup/
    - uses: actions/cache@v4
      name: Cache Solana Tool Suite
      id: cache-solana
      with:
        path: |
          ~/.cache/solana/
          ~/.local/share/solana/
        key: solana-${{ runner.os }}-v0000-${{ env.SOLANA_CLI_VERSION }}

    - run: sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_CLI_VERSION }}/install)"
      shell: bash
      if: steps.cache-solana.outputs.cache-hit != 'true'

    # Set PATH based on OS
    - name: Set Solana PATH
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          echo 'export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"' >> ~/.bashrc
        elif [ "$RUNNER_OS" == "macOS" ]; then
          echo "/Users/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          echo 'export PATH="/Users/runner/.local/share/solana/install/active_release/bin:$PATH"' >> ~/.bash_profile
        fi
      shell: bash

    # Source the profile and verify solana is available
    - name: Verify Solana installation
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          source ~/.bashrc
        elif [ "$RUNNER_OS" == "macOS" ]; then
          source ~/.bash_profile
        fi
        which solana
        solana --version
      shell: bash

    - run: solana-keygen new -s --no-bip39-passphrase --force
      shell: bash

    - run: solana config set --url localhost
      shell: bash
