volumes:
  postgres_data:

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: da_user
      POSTGRES_PASSWORD: da_password
      POSTGRES_DB: da_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U da_user -d da_database"]
      interval: 5s
      timeout: 5s
      retries: 5

  arcium-da-server:
    image: "ghcr.io/elusiv-privacy/arcium-da-server:latest"
    environment:
      DATABASE_URL: postgres://da_user:da_password@db:5432/da_database
      TEST_DATABASE_URL: postgres://da_user:da_password@db:5432/da_database
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: ["/usr/local/bin/da_server"]


  arx-node-0:
    image: "ghcr.io/elusiv-privacy/arx-node:latest"
    environment:
      NODE_IDENTITY_FILE: /usr/arx-node/node-keys/node_identity.pem
      NODE_KEYPAIR_FILE: /usr/arx-node/node-keys/node_keypair.json
      OPERATOR_KEYPAIR_FILE: /usr/arx-node/node-keys/operator_keypair.json
      NODE_CONFIG_PATH: /usr/arx-node/arx/node_config.toml.original
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 5s
    volumes:
      - type: bind
        source: /Users/arihantbansal/Developer/arcium/examples/voting/artifacts/node_config_0.toml
        target: /usr/arx-node/arx/node_config.toml
        read_only: false
      - type: bind
        source: /Users/arihantbansal/Developer/arcium/examples/voting/artifacts/localnet/node_0.json
        target: /usr/arx-node/node-keys/node_keypair.json
      - type: bind
        source: /Users/arihantbansal/Developer/arcium/examples/voting/artifacts/localnet/node_0.json
        target: /usr/arx-node/node-keys/operator_keypair.json
      - type: bind
        source: /Users/arihantbansal/Developer/arcium/examples/voting/artifacts/localnet/identity_0.pem
        target: /usr/arx-node/node-keys/node_identity.pem
      - type: bind
        source: /Users/arihantbansal/Developer/arcium/examples/voting/artifacts/arx_node_logs/node_0.log
        target: /usr/arx-node/arx/logs/info

    extra_hosts:
      - "host.docker.internal:host-gateway"
    
