[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
predictor = "GUDuZTaMjdTJtsHqhBBhcsMDpa5jWRHBDzj5QtB6FL4j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "CQWpCq6BtFGNovpXrrZWtx7jNWz2XKX6yUneKu7rPZbs"
program = "artifacts/arcium_program_0.1.32.so"

[test.validator]
bind_address = "0.0.0.0"
ledger = ".anchor/test-ledger"
rpc_port = 8899


[[test.validator.account]]
address = "VWNZDN2cTXLxJCHecGWRvY5qPHJus1eAVtkAEDNb9iH"
filename = "artifacts/arcium_clock.json"

[[test.validator.account]]
address = "AXih6FLA9s3L5ro73kVKFz9dyYarA1a4hLE7gNqcoKuZ"
filename = "artifacts/arcium_pool.json"

[[test.validator.account]]
address = "67caFht6JPaJzkgbT8EJ8rd7efSVVc65dnNJgvQckwNW"
filename = "artifacts/arcium_pool_ata.json"

[[test.validator.account]]
address = "Hy3G8GVGjGNDLnf6eqBo5gibTiMyjkDYfTgb32VChpq7"
filename = "artifacts/wallet_acc_Hy3G_hpq7.json"

[[test.validator.account]]
address = "BoVUVSJAhob2cvM5z4JZTdS6VWRSznh3bbzQD1TFjvDP"
filename = "artifacts/arx_mint_Hy3G_hpq7.json"

[[test.validator.account]]
address = "AP3CPGx51iNZozrtWdwAQi6f1svLJVfzNsPLwf2Ub3Ed"
filename = "artifacts/arx_ata_user_Hy3G_hpq7.json"

[[test.validator.account]]
address = "C73v5qZpa9pgGoCU2WhGb9gtZDF9f5JbxveLirDY4CKc"
filename = "artifacts/primary_stake_acc_Hy3G_hpq7.json"

[[test.validator.account]]
address = "5AskbXFaHmWfcL6Kg4HUVEQ4jfWZWDEXFWcjJvaeM24F"
filename = "artifacts/stake_queue_acc_Hy3G_hpq7.json"

[[test.validator.account]]
address = "2Sa2DqTbNmsvJ5ssfgRmesSLPpCo4mcyXWihHdrqVV2y"
filename = "artifacts/operator_acc_Hy3G_hpq7.json"

[[test.validator.account]]
address = "7KfGNFoEjWBv3giYW8ZhmJYxZMpDQ8N5VurQV98KAPym"
filename = "artifacts/arx_node_Hy3G_hpq7.json"

[[test.validator.account]]
address = "ariZN4ANYnFyfnF12mmUuCchjawFXnepyrWdEQakFtP"
filename = "artifacts/wallet_acc_ariZ_kFtP.json"

[[test.validator.account]]
address = "BoVUVSJAhob2cvM5z4JZTdS6VWRSznh3bbzQD1TFjvDP"
filename = "artifacts/arx_mint_ariZ_kFtP.json"

[[test.validator.account]]
address = "79hykNQMNeXvcpYDM2buEz1kGNnFBgnGvKPTyTUnCAEj"
filename = "artifacts/arx_ata_user_ariZ_kFtP.json"

[[test.validator.account]]
address = "DFgcMv2v6Pofp4efstBgBGUP241B1pHftsEoSVgf1X6b"
filename = "artifacts/primary_stake_acc_ariZ_kFtP.json"

[[test.validator.account]]
address = "G79scK4hrtbacLwtnUsYbhFcbW6R1jxk3GwLDQnVud8f"
filename = "artifacts/stake_queue_acc_ariZ_kFtP.json"

[[test.validator.account]]
address = "4AXAddC82khUkcEpwVDmdvZ1qgQQqai7DU3NT3fHivkc"
filename = "artifacts/operator_acc_ariZ_kFtP.json"

[[test.validator.account]]
address = "6kQZs3uTZy42aV1wjDTPKST1DJRWjeY3VayyoaRDZYnj"
filename = "artifacts/arx_node_ariZ_kFtP.json"

[[test.validator.account]]
address = "EP5C8AfUNTdP1m41gik4oZzFGRud8ES3e3o2CHmqYtqs"
filename = "artifacts/cluster_acc_0.json"

[[test.validator.account]]
address = "EfgTYR2ryd2CV4hrUDrLoFCM6Yyn8sWsUyrzbX85xSzb"
filename = "artifacts/predict_raw_circuit_0.json"

[[test.validator.account]]
address = "F7jnTm6hWXNW6PNSoiSj2i9kfd2XukLFVfaJfabAN966"
filename = "artifacts/mxe_acc.json"

[[test.validator.account]]
address = "GRno8b2iog9TcGJGhnHQxpG6wXAxT9n9Q7aDhCNxfAg3"
filename = "artifacts/mempool_acc.json"

[[test.validator.account]]
address = "E85ECj19b4UgvJzDQCVTQG7aq4yF7nDRaZVgTAZi6kJD"
filename = "artifacts/executing_pool_acc.json"
