[package]
name = "confidential-ixs"
version = "0.1.0"
edition = "2021"

[features]
default = ["arcis-imports/default"]
solana = ["arcis-imports/solana"]

[dependencies]
arcis-imports = { version = "0.1.37", registry = "arcium", default-features = false }
