[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
rock_paper_scissors_against_rng = "9GfCvW61FrDAJfU5mRVSGcUwY8NDERgrggGjs1Vrxmc8"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
