[package]
name = "confidential-ixs"
version = "0.1.0"
edition = "2021"

[features]
default = ["arcis-imports/default"]
solana = ["arcis-imports/solana"]

[dependencies]
arcis-imports = { path = "/Users/arihantbansal/Developer/arcium/arcium-tooling/arcis-imports", default-features = false }
