name: Clippy Check
on:
  workflow_run:
    workflows: ["Formatting Check"]
    types:
      - completed

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup/

      # Find all example directories
      - name: Find example directories
        id: find-examples
        run: |
          echo "examples=$(find . -type f -name "Anchor.toml" -exec dirname {} \; | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

      # Run clippy on each example
      - name: Run clippy
        run: |
          EXAMPLES=$(echo '${{ steps.find-examples.outputs.examples }}' | jq -r '.[]')
          for example in $EXAMPLES; do
            echo "Running clippy in $example"
            cd $example
            cargo clippy --all-targets -- -D warnings
            cd $GITHUB_WORKSPACE
          done
