name: Debug Secrets
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  debug:
    name: Debug Environment
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      # Debug secrets and environment
      - name: Debug Secrets
        env:
          ARCUP_TOKEN: ${{ secrets.ARCUP_TOKEN }}
        run: |
          echo "Checking secrets..."
          echo "Is ARCUP_TOKEN defined? [[ -n '${{ secrets.ARCUP_TOKEN }}' ]] && echo 'yes' || echo 'no'"
          echo "ARCUP_TOKEN length: ${#ARCUP_TOKEN}"
          echo "First character of token: ${ARCUP_TOKEN:0:1}"
          echo "Environment dump (safe values only):"
          env | grep -v 'TOKEN\|KEY\|SECRET\|PASSWORD'
